defaultChannel : mychannel
caConfig:
   caUrl : http://192.168.136.131:7054
channels:
   -
      channelName: mychannel
      peers:
         peer1: 192.168.136.131:7051
      orderers:
         orderer1: 192.168.136.131:7050

users:
   -
      username: admin
      password: adminpw
      org: org1
      mspId: Org1MSP

defaultUser: admin