// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Persistence.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 操作类型
type OPType int32

const (
	OPType_CREATED   OPType = 0
	OPType_LOGISTICS OPType = 1
	OPType_DELIVERED OPType = 2
)

var OPType_name = map[int32]string{
	0: "CREATED",
	1: "LOGISTICS",
	2: "DELIVERED",
}
var OPType_value = map[string]int32{
	"CREATED":   0,
	"LOGISTICS": 1,
	"DELIVERED": 2,
}

func (x OPType) String() string {
	return proto.EnumName(OPType_name, int32(x))
}
func (OPType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// 地址信息
type Address struct {
	Name      string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Desc      string  `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude" json:"longitude,omitempty"`
	Latitude  float64 `protobuf:"fixed64,4,opt,name=latitude" json:"latitude,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Address) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Address) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Address) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Address) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

// 环境信息，目前只有地址
type EnvStatus struct {
	Address *Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *EnvStatus) Reset()                    { *m = EnvStatus{} }
func (m *EnvStatus) String() string            { return proto.CompactTextString(m) }
func (*EnvStatus) ProtoMessage()               {}
func (*EnvStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *EnvStatus) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

// 操作信息，
type OpsStatus struct {
	CurrentOrg string `protobuf:"bytes,1,opt,name=currentOrg" json:"currentOrg,omitempty"`
	LastOrg    string `protobuf:"bytes,2,opt,name=lastOrg" json:"lastOrg,omitempty"`
	OpType     OPType `protobuf:"varint,3,opt,name=opType,enum=OPType" json:"opType,omitempty"`
	ContactWay string `protobuf:"bytes,4,opt,name=contactWay" json:"contactWay,omitempty"`
}

func (m *OpsStatus) Reset()                    { *m = OpsStatus{} }
func (m *OpsStatus) String() string            { return proto.CompactTextString(m) }
func (*OpsStatus) ProtoMessage()               {}
func (*OpsStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *OpsStatus) GetCurrentOrg() string {
	if m != nil {
		return m.CurrentOrg
	}
	return ""
}

func (m *OpsStatus) GetLastOrg() string {
	if m != nil {
		return m.LastOrg
	}
	return ""
}

func (m *OpsStatus) GetOpType() OPType {
	if m != nil {
		return m.OpType
	}
	return OPType_CREATED
}

func (m *OpsStatus) GetContactWay() string {
	if m != nil {
		return m.ContactWay
	}
	return ""
}

// 商品信息
type ItemInfo struct {
	Name            string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Class           string `protobuf:"bytes,2,opt,name=class" json:"class,omitempty"`
	BatchNumber     string `protobuf:"bytes,3,opt,name=batchNumber" json:"batchNumber,omitempty"`
	ManufactureDate int64  `protobuf:"varint,4,opt,name=manufactureDate" json:"manufactureDate,omitempty"`
	Note            string `protobuf:"bytes,5,opt,name=note" json:"note,omitempty"`
}

func (m *ItemInfo) Reset()                    { *m = ItemInfo{} }
func (m *ItemInfo) String() string            { return proto.CompactTextString(m) }
func (*ItemInfo) ProtoMessage()               {}
func (*ItemInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ItemInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ItemInfo) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *ItemInfo) GetBatchNumber() string {
	if m != nil {
		return m.BatchNumber
	}
	return ""
}

func (m *ItemInfo) GetManufactureDate() int64 {
	if m != nil {
		return m.ManufactureDate
	}
	return 0
}

func (m *ItemInfo) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

// 商品状态
type ItemStatus struct {
	SampleStrStatus  string `protobuf:"bytes,1,opt,name=sampleStrStatus" json:"sampleStrStatus,omitempty"`
	SampleLongStatus int64  `protobuf:"varint,2,opt,name=sampleLongStatus" json:"sampleLongStatus,omitempty"`
	Logs             string `protobuf:"bytes,3,opt,name=logs" json:"logs,omitempty"`
}

func (m *ItemStatus) Reset()                    { *m = ItemStatus{} }
func (m *ItemStatus) String() string            { return proto.CompactTextString(m) }
func (*ItemStatus) ProtoMessage()               {}
func (*ItemStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ItemStatus) GetSampleStrStatus() string {
	if m != nil {
		return m.SampleStrStatus
	}
	return ""
}

func (m *ItemStatus) GetSampleLongStatus() int64 {
	if m != nil {
		return m.SampleLongStatus
	}
	return 0
}

func (m *ItemStatus) GetLogs() string {
	if m != nil {
		return m.Logs
	}
	return ""
}

// 主要的商品资产描述
type ItemAsset struct {
	Timestamp  int64       `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	ItemId     string      `protobuf:"bytes,2,opt,name=itemId" json:"itemId,omitempty"`
	ItemInfo   *ItemInfo   `protobuf:"bytes,3,opt,name=itemInfo" json:"itemInfo,omitempty"`
	ItemStatus *ItemStatus `protobuf:"bytes,4,opt,name=itemStatus" json:"itemStatus,omitempty"`
	EvnStatus  *EnvStatus  `protobuf:"bytes,5,opt,name=evnStatus" json:"evnStatus,omitempty"`
	OpsStatus  *OpsStatus  `protobuf:"bytes,6,opt,name=opsStatus" json:"opsStatus,omitempty"`
}

func (m *ItemAsset) Reset()                    { *m = ItemAsset{} }
func (m *ItemAsset) String() string            { return proto.CompactTextString(m) }
func (*ItemAsset) ProtoMessage()               {}
func (*ItemAsset) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ItemAsset) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ItemAsset) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *ItemAsset) GetItemInfo() *ItemInfo {
	if m != nil {
		return m.ItemInfo
	}
	return nil
}

func (m *ItemAsset) GetItemStatus() *ItemStatus {
	if m != nil {
		return m.ItemStatus
	}
	return nil
}

func (m *ItemAsset) GetEvnStatus() *EnvStatus {
	if m != nil {
		return m.EvnStatus
	}
	return nil
}

func (m *ItemAsset) GetOpsStatus() *OpsStatus {
	if m != nil {
		return m.OpsStatus
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "Address")
	proto.RegisterType((*EnvStatus)(nil), "EnvStatus")
	proto.RegisterType((*OpsStatus)(nil), "OpsStatus")
	proto.RegisterType((*ItemInfo)(nil), "ItemInfo")
	proto.RegisterType((*ItemStatus)(nil), "ItemStatus")
	proto.RegisterType((*ItemAsset)(nil), "ItemAsset")
	proto.RegisterEnum("OPType", OPType_name, OPType_value)
}

func init() { proto.RegisterFile("Persistence.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xef, 0x8a, 0xd3, 0x4e,
	0x14, 0xfd, 0xa5, 0xff, 0x73, 0xc3, 0xcf, 0xad, 0x83, 0x48, 0x10, 0xd1, 0x12, 0x10, 0x4a, 0x85,
	0x08, 0xdd, 0x27, 0xa8, 0xdb, 0x20, 0x85, 0x62, 0x97, 0x69, 0x51, 0xf0, 0xdb, 0x34, 0x99, 0xd6,
	0x68, 0x32, 0x13, 0x66, 0x6e, 0x2a, 0xfb, 0x02, 0x3e, 0x81, 0x2f, 0xe9, 0x5b, 0xc8, 0x4c, 0xa6,
	0x69, 0x59, 0xfd, 0x36, 0xe7, 0x9c, 0x9b, 0x39, 0x67, 0x0e, 0x37, 0xf0, 0xf4, 0x9e, 0x2b, 0x9d,
	0x6b, 0xe4, 0x22, 0xe5, 0x71, 0xa5, 0x24, 0xca, 0xe8, 0x3b, 0x0c, 0x17, 0x59, 0xa6, 0xb8, 0xd6,
	0x84, 0x40, 0x4f, 0xb0, 0x92, 0x87, 0xde, 0xc4, 0x9b, 0xfa, 0xd4, 0x9e, 0x0d, 0x97, 0x71, 0x9d,
	0x86, 0x9d, 0x86, 0x33, 0x67, 0xf2, 0x12, 0xfc, 0x42, 0x8a, 0x63, 0x8e, 0x75, 0xc6, 0xc3, 0xee,
	0xc4, 0x9b, 0x7a, 0xf4, 0x42, 0x90, 0x17, 0x30, 0x2a, 0x18, 0x36, 0x62, 0xcf, 0x8a, 0x2d, 0x8e,
	0xde, 0x81, 0x9f, 0x88, 0xd3, 0x16, 0x19, 0xd6, 0x9a, 0x44, 0x30, 0x64, 0x8d, 0xb3, 0x75, 0x0c,
	0xe6, 0xa3, 0xd8, 0x25, 0xa1, 0x67, 0x21, 0xfa, 0xe9, 0x81, 0xbf, 0xa9, 0xb4, 0xfb, 0xe2, 0x15,
	0x40, 0x5a, 0x2b, 0xc5, 0x05, 0x6e, 0xd4, 0xd1, 0xc5, 0xbc, 0x62, 0x48, 0x08, 0xc3, 0x82, 0x69,
	0x2b, 0x36, 0x79, 0xcf, 0x90, 0xbc, 0x86, 0x81, 0xac, 0x76, 0x0f, 0x55, 0x93, 0xf7, 0xc9, 0x7c,
	0x18, 0x6f, 0xee, 0x0d, 0xa4, 0x8e, 0xb6, 0x57, 0x4b, 0x81, 0x2c, 0xc5, 0xcf, 0xec, 0xc1, 0xe6,
	0x36, 0x57, 0xb7, 0x4c, 0xf4, 0xcb, 0x83, 0xd1, 0x0a, 0x79, 0xb9, 0x12, 0x07, 0xf9, 0xcf, 0xa2,
	0x9e, 0x41, 0x3f, 0x2d, 0x98, 0xd6, 0xce, 0xb9, 0x01, 0x64, 0x02, 0xc1, 0x9e, 0x61, 0xfa, 0xf5,
	0x63, 0x5d, 0xee, 0xb9, 0xb2, 0xe6, 0x3e, 0xbd, 0xa6, 0xc8, 0x14, 0x6e, 0x4a, 0x26, 0xea, 0x03,
	0x4b, 0xb1, 0x56, 0x7c, 0xc9, 0xb0, 0x69, 0xad, 0x4b, 0x1f, 0xd3, 0xd6, 0x55, 0x22, 0x0f, 0xfb,
	0xce, 0x55, 0x22, 0x8f, 0x4e, 0x00, 0x26, 0x95, 0xeb, 0x67, 0x0a, 0x37, 0x9a, 0x95, 0x55, 0xc1,
	0xb7, 0xa8, 0x1a, 0xca, 0x45, 0x7c, 0x4c, 0x93, 0x19, 0x8c, 0x1b, 0x6a, 0x2d, 0xc5, 0xd1, 0x8d,
	0x76, 0xac, 0xed, 0x5f, 0xbc, 0xf1, 0x2d, 0xe4, 0x51, 0xbb, 0xf0, 0xf6, 0x1c, 0xfd, 0xf6, 0xc0,
	0x37, 0xc6, 0x0b, 0xad, 0x39, 0x9a, 0x85, 0xc0, 0xbc, 0xe4, 0x1a, 0x59, 0x59, 0x59, 0xc7, 0x2e,
	0xbd, 0x10, 0xe4, 0x39, 0x0c, 0x72, 0xd3, 0x5c, 0xe6, 0xaa, 0x71, 0x88, 0xbc, 0x81, 0x51, 0xee,
	0x1a, 0xb5, 0x77, 0x07, 0x73, 0x3f, 0x3e, 0x57, 0x4c, 0x5b, 0x89, 0xbc, 0x05, 0xc8, 0xdb, 0x27,
	0xda, 0x6e, 0x82, 0x79, 0x10, 0x5f, 0x5e, 0x4d, 0xaf, 0x64, 0x32, 0x05, 0x9f, 0x9f, 0x84, 0x9b,
	0xed, 0xdb, 0x59, 0x88, 0xdb, 0x95, 0xa3, 0x17, 0xd1, 0x4c, 0xca, 0xf3, 0x62, 0x85, 0x03, 0x37,
	0xd9, 0xae, 0x1a, 0xbd, 0x88, 0xb3, 0x5b, 0x18, 0x34, 0xcb, 0x42, 0x02, 0x18, 0xde, 0xd1, 0x64,
	0xb1, 0x4b, 0x96, 0xe3, 0xff, 0xc8, 0xff, 0xe0, 0xaf, 0x37, 0x1f, 0x56, 0xdb, 0xdd, 0xea, 0x6e,
	0x3b, 0xf6, 0x0c, 0x5c, 0x26, 0xeb, 0xd5, 0xa7, 0x84, 0x26, 0xcb, 0x71, 0xe7, 0xfd, 0x1c, 0x66,
	0xa9, 0x88, 0x79, 0x56, 0xc7, 0xe2, 0x5b, 0x1d, 0x6b, 0x79, 0xc0, 0x1f, 0x4c, 0xf1, 0xf8, 0xc0,
	0xf6, 0x2a, 0x4f, 0x35, 0x57, 0xa7, 0xfc, 0xfc, 0x07, 0x96, 0xfa, 0xf8, 0xa5, 0x57, 0xb2, 0x5c,
	0xec, 0x07, 0x16, 0xdf, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xef, 0x99, 0xe9, 0x7d, 0xa6, 0x03,
	0x00, 0x00,
}
