// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Persistence.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 操作类型
type OPType int32

const (
	// 出厂
	OPType_CREATED OPType = 0
	// 出售给分销商/代理商
	OPType_TRANSFER OPType = 1
	// 中转
	OPType_MEDIA OPType = 2
	// 入库
	OPType_INSTOCK OPType = 3
	// 出库
	OPType_OUTSTOCK OPType = 4
	// 送达
	OPType_DELIVERED OPType = 5
)

var OPType_name = map[int32]string{
	0: "CREATED",
	1: "TRANSFER",
	2: "MEDIA",
	3: "INSTOCK",
	4: "OUTSTOCK",
	5: "DELIVERED",
}
var OPType_value = map[string]int32{
	"CREATED":   0,
	"TRANSFER":  1,
	"MEDIA":     2,
	"INSTOCK":   3,
	"OUTSTOCK":  4,
	"DELIVERED": 5,
}

func (x OPType) String() string {
	return proto.EnumName(OPType_name, int32(x))
}
func (OPType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// 地址信息
type Address struct {
	Name      string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Desc      string  `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude" json:"longitude,omitempty"`
	Latitude  float64 `protobuf:"fixed64,4,opt,name=latitude" json:"latitude,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Address) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Address) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Address) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Address) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

// 环境信息，目前只有地址
type EnvStatus struct {
	Address *Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *EnvStatus) Reset()                    { *m = EnvStatus{} }
func (m *EnvStatus) String() string            { return proto.CompactTextString(m) }
func (*EnvStatus) ProtoMessage()               {}
func (*EnvStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *EnvStatus) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

// 操作信息
type OpsStatus struct {
	CurrentOrg string `protobuf:"bytes,1,opt,name=currentOrg" json:"currentOrg,omitempty"`
	LastOrg    string `protobuf:"bytes,2,opt,name=lastOrg" json:"lastOrg,omitempty"`
	OpType     OPType `protobuf:"varint,3,opt,name=opType,enum=OPType" json:"opType,omitempty"`
	ContactWay string `protobuf:"bytes,4,opt,name=contactWay" json:"contactWay,omitempty"`
	ExtraInfo  string `protobuf:"bytes,5,opt,name=extraInfo" json:"extraInfo,omitempty"`
}

func (m *OpsStatus) Reset()                    { *m = OpsStatus{} }
func (m *OpsStatus) String() string            { return proto.CompactTextString(m) }
func (*OpsStatus) ProtoMessage()               {}
func (*OpsStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *OpsStatus) GetCurrentOrg() string {
	if m != nil {
		return m.CurrentOrg
	}
	return ""
}

func (m *OpsStatus) GetLastOrg() string {
	if m != nil {
		return m.LastOrg
	}
	return ""
}

func (m *OpsStatus) GetOpType() OPType {
	if m != nil {
		return m.OpType
	}
	return OPType_CREATED
}

func (m *OpsStatus) GetContactWay() string {
	if m != nil {
		return m.ContactWay
	}
	return ""
}

func (m *OpsStatus) GetExtraInfo() string {
	if m != nil {
		return m.ExtraInfo
	}
	return ""
}

// 商品信息
type ItemInfo struct {
	Name            string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Class           string `protobuf:"bytes,2,opt,name=class" json:"class,omitempty"`
	BatchNumber     string `protobuf:"bytes,3,opt,name=batchNumber" json:"batchNumber,omitempty"`
	ManufactureDate int64  `protobuf:"varint,4,opt,name=manufactureDate" json:"manufactureDate,omitempty"`
	Note            string `protobuf:"bytes,5,opt,name=note" json:"note,omitempty"`
}

func (m *ItemInfo) Reset()                    { *m = ItemInfo{} }
func (m *ItemInfo) String() string            { return proto.CompactTextString(m) }
func (*ItemInfo) ProtoMessage()               {}
func (*ItemInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ItemInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ItemInfo) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *ItemInfo) GetBatchNumber() string {
	if m != nil {
		return m.BatchNumber
	}
	return ""
}

func (m *ItemInfo) GetManufactureDate() int64 {
	if m != nil {
		return m.ManufactureDate
	}
	return 0
}

func (m *ItemInfo) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

// 商品状态
type ItemStatus struct {
	Normal bool   `protobuf:"varint,1,opt,name=normal" json:"normal,omitempty"`
	Logs   string `protobuf:"bytes,2,opt,name=logs" json:"logs,omitempty"`
}

func (m *ItemStatus) Reset()                    { *m = ItemStatus{} }
func (m *ItemStatus) String() string            { return proto.CompactTextString(m) }
func (*ItemStatus) ProtoMessage()               {}
func (*ItemStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ItemStatus) GetNormal() bool {
	if m != nil {
		return m.Normal
	}
	return false
}

func (m *ItemStatus) GetLogs() string {
	if m != nil {
		return m.Logs
	}
	return ""
}

// 主要的商品资产描述
type ItemAsset struct {
	Timestamp  int64       `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	ItemId     string      `protobuf:"bytes,2,opt,name=itemId" json:"itemId,omitempty"`
	ItemInfo   *ItemInfo   `protobuf:"bytes,3,opt,name=itemInfo" json:"itemInfo,omitempty"`
	ItemStatus *ItemStatus `protobuf:"bytes,4,opt,name=itemStatus" json:"itemStatus,omitempty"`
	EvnStatus  *EnvStatus  `protobuf:"bytes,5,opt,name=evnStatus" json:"evnStatus,omitempty"`
	OpsStatus  *OpsStatus  `protobuf:"bytes,6,opt,name=opsStatus" json:"opsStatus,omitempty"`
}

func (m *ItemAsset) Reset()                    { *m = ItemAsset{} }
func (m *ItemAsset) String() string            { return proto.CompactTextString(m) }
func (*ItemAsset) ProtoMessage()               {}
func (*ItemAsset) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ItemAsset) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ItemAsset) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *ItemAsset) GetItemInfo() *ItemInfo {
	if m != nil {
		return m.ItemInfo
	}
	return nil
}

func (m *ItemAsset) GetItemStatus() *ItemStatus {
	if m != nil {
		return m.ItemStatus
	}
	return nil
}

func (m *ItemAsset) GetEvnStatus() *EnvStatus {
	if m != nil {
		return m.EvnStatus
	}
	return nil
}

func (m *ItemAsset) GetOpsStatus() *OpsStatus {
	if m != nil {
		return m.OpsStatus
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "Address")
	proto.RegisterType((*EnvStatus)(nil), "EnvStatus")
	proto.RegisterType((*OpsStatus)(nil), "OpsStatus")
	proto.RegisterType((*ItemInfo)(nil), "ItemInfo")
	proto.RegisterType((*ItemStatus)(nil), "ItemStatus")
	proto.RegisterType((*ItemAsset)(nil), "ItemAsset")
	proto.RegisterEnum("OPType", OPType_name, OPType_value)
}

func init() { proto.RegisterFile("Persistence.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xdb, 0x8e, 0xd3, 0x30,
	0x10, 0x25, 0xdb, 0x5b, 0x32, 0xe1, 0x52, 0x2c, 0x84, 0x22, 0x84, 0xa0, 0x8a, 0x84, 0x54, 0x2d,
	0x92, 0x91, 0xca, 0x0b, 0xaf, 0x65, 0x1b, 0xa4, 0x0a, 0x68, 0x57, 0x6e, 0xb9, 0x88, 0x37, 0x37,
	0x71, 0x4b, 0x20, 0xb1, 0x2b, 0xdb, 0x29, 0xec, 0x7f, 0xf0, 0x09, 0xfc, 0x1c, 0x7f, 0x81, 0xec,
	0x38, 0x49, 0x85, 0x78, 0x9b, 0x73, 0xce, 0xcc, 0xf8, 0xcc, 0x68, 0x0c, 0xf7, 0xaf, 0x99, 0x54,
	0xb9, 0xd2, 0x8c, 0xa7, 0x0c, 0x1f, 0xa5, 0xd0, 0x22, 0xfe, 0x0e, 0xa3, 0x79, 0x96, 0x49, 0xa6,
	0x14, 0x42, 0xd0, 0xe7, 0xb4, 0x64, 0x91, 0x37, 0xf1, 0xa6, 0x01, 0xb1, 0xb1, 0xe1, 0x32, 0xa6,
	0xd2, 0xe8, 0xa2, 0xe6, 0x4c, 0x8c, 0x1e, 0x43, 0x50, 0x08, 0x7e, 0xc8, 0x75, 0x95, 0xb1, 0xa8,
	0x37, 0xf1, 0xa6, 0x1e, 0xe9, 0x08, 0xf4, 0x08, 0xfc, 0x82, 0xea, 0x5a, 0xec, 0x5b, 0xb1, 0xc5,
	0xf1, 0x0b, 0x08, 0x12, 0x7e, 0xda, 0x68, 0xaa, 0x2b, 0x85, 0x62, 0x18, 0xd1, 0xfa, 0x65, 0xfb,
	0x62, 0x38, 0xf3, 0xb1, 0x73, 0x42, 0x1a, 0x21, 0xfe, 0xed, 0x41, 0xb0, 0x3e, 0x2a, 0x57, 0xf1,
	0x04, 0x20, 0xad, 0xa4, 0x64, 0x5c, 0xaf, 0xe5, 0xc1, 0xd9, 0x3c, 0x63, 0x50, 0x04, 0xa3, 0x82,
	0x2a, 0x2b, 0xd6, 0x7e, 0x1b, 0x88, 0x9e, 0xc2, 0x50, 0x1c, 0xb7, 0x37, 0xc7, 0xda, 0xef, 0xdd,
	0xd9, 0x08, 0xaf, 0xaf, 0x0d, 0x24, 0x8e, 0xb6, 0xad, 0x05, 0xd7, 0x34, 0xd5, 0x9f, 0xe8, 0x8d,
	0xf5, 0x6d, 0x5a, 0xb7, 0x8c, 0x99, 0x99, 0xfd, 0xd4, 0x92, 0x2e, 0xf9, 0x5e, 0x44, 0x03, 0x2b,
	0x77, 0x44, 0xfc, 0xcb, 0x03, 0x7f, 0xa9, 0x59, 0x69, 0xc0, 0x7f, 0xd7, 0xf8, 0x00, 0x06, 0x69,
	0x41, 0x95, 0x72, 0xbe, 0x6a, 0x80, 0x26, 0x10, 0xee, 0xa8, 0x4e, 0xbf, 0xae, 0xaa, 0x72, 0xc7,
	0xa4, 0xb5, 0x16, 0x90, 0x73, 0x0a, 0x4d, 0xe1, 0x5e, 0x49, 0x79, 0xb5, 0xa7, 0xa9, 0xae, 0x24,
	0x5b, 0x50, 0x5d, 0xef, 0xb4, 0x47, 0xfe, 0xa5, 0xed, 0xab, 0x42, 0x33, 0xe7, 0xcd, 0xc6, 0xf1,
	0x2b, 0x00, 0xe3, 0xca, 0x6d, 0xef, 0x21, 0x0c, 0xb9, 0x90, 0x25, 0x2d, 0xac, 0x33, 0x9f, 0x38,
	0x64, 0x2a, 0x0b, 0x71, 0x68, 0xac, 0xd9, 0x38, 0xfe, 0xe3, 0x41, 0x60, 0x4a, 0xe7, 0x4a, 0x31,
	0x6d, 0x86, 0xd7, 0x79, 0xc9, 0x94, 0xa6, 0xe5, 0xd1, 0x16, 0xf7, 0x48, 0x47, 0x98, 0xbe, 0xb9,
	0x99, 0x3d, 0x73, 0x1d, 0x1c, 0x42, 0xcf, 0xc0, 0xcf, 0xdd, 0x4e, 0xec, 0x68, 0xe1, 0x2c, 0xc0,
	0xcd, 0x92, 0x48, 0x2b, 0xa1, 0xe7, 0x00, 0x79, 0x6b, 0xd2, 0x4e, 0x17, 0xce, 0x42, 0xdc, 0xf9,
	0x26, 0x67, 0x32, 0x9a, 0x42, 0xc0, 0x4e, 0xdc, 0xe5, 0x0e, 0x6c, 0x2e, 0xe0, 0xf6, 0xa4, 0x48,
	0x27, 0x9a, 0x4c, 0xd1, 0x1c, 0x4e, 0x34, 0x74, 0x99, 0xed, 0x29, 0x91, 0x4e, 0xbc, 0xfc, 0x0c,
	0xc3, 0xfa, 0x18, 0x50, 0x08, 0xa3, 0x2b, 0x92, 0xcc, 0xb7, 0xc9, 0x62, 0x7c, 0x0b, 0xdd, 0x06,
	0x7f, 0x4b, 0xe6, 0xab, 0xcd, 0x9b, 0x84, 0x8c, 0x3d, 0x14, 0xc0, 0xe0, 0x7d, 0xb2, 0x58, 0xce,
	0xc7, 0x17, 0x26, 0x6b, 0xb9, 0xda, 0x6c, 0xd7, 0x57, 0x6f, 0xc7, 0x3d, 0x93, 0xb5, 0xfe, 0xb0,
	0xad, 0x51, 0x1f, 0xdd, 0x81, 0x60, 0x91, 0xbc, 0x5b, 0x7e, 0x4c, 0x48, 0xb2, 0x18, 0x0f, 0x5e,
	0xcf, 0xe0, 0x32, 0xe5, 0x98, 0x65, 0x15, 0xe6, 0xdf, 0x2a, 0xac, 0xc4, 0x5e, 0xff, 0xa0, 0x92,
	0xe1, 0x3d, 0xdd, 0xc9, 0x3c, 0x55, 0x4c, 0x9e, 0xf2, 0xe6, 0x1b, 0x96, 0xea, 0xf0, 0xa5, 0x5f,
	0xd2, 0x9c, 0xef, 0x86, 0x16, 0xbf, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xee, 0x00, 0x90, 0x44,
	0xab, 0x03, 0x00, 0x00,
}
